### ISSUE TITLE
, button doesn't work as expected

### ISSUE THREAD

**Issue by dorufoaltin** [Alexandru199205/CalculatorTest#10]
if you try to add 1,1 + 1,2 the result is 23 instead of 2,3

**Comment by Alexandru199205** [comment]
I hope I solved it. @dorufoaltin

**Comment by Dorin-Foaltin** [comment]
@Alexandru199205 :sorry, it still doesn't work on my PC. 

I see you have changed the culture to en-US on the entire application, which is not usually a good practice, AND en-US culture is the culture I am using and it is not working. 

Most probably you are using ro culture. 
In order to properly fix this, you need to specify which culture should be used for all parse methods, like this: 

![image](https://user-images.githubusercontent.com/75241559/139018199-cd299cdb-6d57-4bd6-8c3a-79085b2b21eb.png)

PS: In order to test this, you can change the culture of your PC by going to settings, and change the regional format to United States, like this: 

![image](https://user-images.githubusercontent.com/75241559/139018351-be762de4-0fe2-44c8-a7b5-9d65a322f35a.png)
