### ISSUE TITLE
Add better indentation (formatting) of the C# code

### ISSUE THREAD

**Issue by dorufoaltin** [Alexandru199205/CalculatorTest#11]
Being able to easily read the code is very important, especially when working within a team. When another team mate wants to read your code, or you will try to read the code after several years, this should be as easily as possible.

Formatting so all rows text starts properly is very easy, and helps a lot in reading the code. You can easily do this via visual studio format shortcut: **ctrl + e + d**, or **ctrl + k + d**. 

For example, this: 

![image](https://user-images.githubusercontent.com/6756850/134344697-8a466349-8978-42a4-a38c-b2658e6f5bf8.png)

Would look like this: 
![image](https://user-images.githubusercontent.com/6756850/134344800-4712427b-f3d4-4098-8d2e-78087ffdaa5e.png)

**Comment by Dorin-Foaltin** [comment]
Nice, code is starting to look professional!

Tip: try to remember the shortcut, and incorporate it in your routine, for example, every time I type some code I end up with applying the shortcut, this way, it is always formatted. Or maybe just apply the formatting before committing any new changes in git.

I say this because the new code introduced is not all formatted: 
![image](https://user-images.githubusercontent.com/75241559/138223721-342567ab-aa84-468a-94f2-a0abfd891609.png)
