### ISSUE TITLE
Fix value too large exception

### ISSUE THREAD

**Issue by dorufoaltin** [Alexandru199205/CalculatorTest#5]
When trying to multiply 2 numbers that are very big, your app crashes. Try to always fix all the corner cases like this, it's the best way to learn. 

Here's the crash in code: 

![image](https://user-images.githubusercontent.com/6756850/132187514-c21476f5-f8ab-46f7-aaa9-f965211afa14.png)

**Comment by Alexandru199205** [comment]
I will change the type in order to avoid the crash. I will also pay a bit more with it in order to see if there are any more issues.
Thanks a lot.

**Comment by Alexandru199205** [comment]
Solve it as described above @dorufoaltin

**Comment by Dorin-Foaltin** [comment]
The app doesn't crash anymore, but this time, the result of multiplying 2 large numbers will result in wrong result, because the value will exceed long type max value.

Considering that both [long](https://www.google.com/search?q=c%23+long+max+value&oq=C%23+long+max+value&aqs=chrome.0.69i59j0i22i30l4j69i58.2480j0j7&sourceid=chrome&ie=UTF-8) and [decimal](https://www.google.com/search?q=c%23+decimal+max+value&sxsrf=AOaemvLMzv-jfPVzMW08Vr6HssDJSiOoZQ%3A1631174721495&ei=QcA5YbTJHYe2kwWOhqW4DQ&oq=c%23+decimal+max+value&gs_lcp=Cgdnd3Mtd2l6EAMyBAgjECcyBggAEAcQHjIGCAAQBxAeMgUIABCABDoHCCMQsAMQJzoHCAAQRxCwAzoHCAAQsAMQQzoICAAQCBAHEB46BAgAEA06BggAEA0QHjoHCCMQsAIQJ0oECEEYAFD5dVjHfmDShgFoAnACeACAAaEBiAG7B5IBAzIuNpgBAKABAcgBCsABAQ&sclient=gws-wiz&ved=0ahUKEwj07dyut_HyAhUH26QKHQ5DCdcQ4dUDCA4&uact=5) types have a max value, you have to check what will happen when a value close to this is used in multiplication scenario.  

Eg: I checked 8.999.999.999.999.999.999 * 8.999.999.999.999.999.999, and the result was a negative number (because the result value has exceeded the max value, and the new resulted bites of that long was representing a negative number). 

In order to fix this, I would **use double instead**, which still has a max value, but this is very large, 1.7976931348623157E+308, and the result of an operation that will exceed this value will not misbehave, but result into positive infinity, check [this link](https://docs.microsoft.com/en-us/dotnet/api/system.double.maxvalue?view=net-5.0) for the details.
