### ISSUE TITLE
Capture keyboard input from the entire form, not only while textbox is focused

### ISSUE THREAD

**Issue by dorufoaltin** [Alexandru199205/CalculatorTest#8]
Currently only if you click/ focus the textbox via tab the calculator will handle keyboard input for formulas like 1 + 1 =, but this should work without click on textbox. 

You can do this by setting KeyPreview = True on form's properties: 

![image](https://user-images.githubusercontent.com/6756850/134342565-f69ab10a-e64a-4192-9f04-f1f84b78c67f.png)

**Comment by Dorin-Foaltin** [comment]
I see that you have set the textbox to be focused at app start, thus improving the keyboard experience, but it still doesn't cover all the cases, and I would still improve it, by using the above implementation. 

Currently this scenario doesn't work: 

1. Click with the mouse on any button eg: 1
2. Press a keyboard key eg: 2 

the key pressed is not recognized (because the focus has changed from the textbox to the button).
